FROM php:8.1-fpm

# تثبيت التبعيات
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim unzip git curl

# تثبيت composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# إعداد مجلد العمل
WORKDIR /var/www

# نسخ المشروع إلى الحاوية
COPY . .

# تثبيت الاعتماديات
RUN composer install --no-dev --optimize-autoloader

# إعداد صلاحيات
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# ضبط المتغيرات
ENV APP_ENV=production
ENV APP_DEBUG=false

# تشغيل السيرفر
CMD php artisan serve --host=0.0.0.0 --port=8000

EXPOSE 8000
